baseURL = 'https://liuchang0812.github.io/'
languageCode = 'zh-cn'
title = 'Liu Chang Blog'
theme = "PaperMod"
enableInlineShortcodes=true
enableEmoji=true
enableRobotsTXT=true
hasCJKLanguage=true

[outputs]
home=['HTML', 'RSS', 'JSON']

[params]
ShowCodeCopyButtons=true
ShowPostNavLinks=true
ShowReadingTime=true

ShowToc=true
TocOpen=false

[markup]
[markup.highlight]
  lineNos=true
  style='monokai'
  tabWidth = 2

[menu]
[[menu.main]]
  name = 'ğŸ™‹ğŸ»â€â™‚ï¸å…³äº'
  url = '/about/'
  weight=3

[[menu.main]]
  name='â±æ—¶é—´è½´'
  url='/archives/'
  weight=2

[[menu.main]]
  name='ğŸ”æœç´¢'
  url='/search/'
  weight=1
