baseURL = 'https://liuchang0812.github.io/'
languageCode = 'zh-cn'
title = 'Liu Chang Blog'
theme = "PaperMod"
enableInlineShortcodes=true
enableEmoji=true
enableRobotsTXT=true
hasCJKLanguage=true

[outputs]
home=['HTML', 'RSS', 'JSON']

[params]
ShowCodeCopyButtons=true
ShowPostNavLinks=true
ShowReadingTime=true

ShowToc=true
TocOpen=false

[markup]
[[markup.highlight]]
  lineNos=true
  style='monokai'

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'about'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight=1

[[menu.main]]
  name='â±æ—¶é—´è½´'
  url='/archives/'
  weight=2

[[menu.main]]
  name='ğŸ”æœç´¢'
  url='/search/'
  weight=3
